name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: numeric

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/cabukege/numeric:latest

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        
      - name: Start Minikube tunnel
        run: minikube tunnel &

      - name: Enable Ingress addon
        run: minikube addons enable ingress

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml
          
      - name: Wait for deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/numeric-api-deployment
          
      - name: Get deployment status
        run: |
          echo "Deployment Status:"
          kubectl get deployments
          echo "\nPod Status:"
          kubectl get pods
          echo "\nService Status:"
          kubectl get services
          echo "\nMinikube Services:"
          minikube service list